import PDFDocument from 'pdfkit';
import type { ScanResult } from '../engine/types';

const COLORS = {
  primary: '#6d5efc',
  dark: '#0b1020',
  text: '#1f2937',
  muted: '#6b7280',
  safe: '#22c55e',
  moderate: '#f59e0b',
  high: '#ef4444',
};

function levelColor(level: string): string {
  if (level === 'Safe') return COLORS.safe;
  if (level === 'Moderate') return COLORS.moderate;
  return COLORS.high;
}

/** Streams a PDF report for a scan result into the given writable stream. */
export function generateScanPdf(result: ScanResult): PDFKit.PDFDocument {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  // Header band
  doc.rect(0, 0, doc.page.width, 90).fill(COLORS.dark);
  doc.fillColor('#ffffff').fontSize(22).text('AI Security Intelligence Platform', 50, 30);
  doc.fillColor('#9aa4d4').fontSize(11).text('Website Security Scan Report', 50, 60);
  doc.moveDown(2);

  // Target + meta
  doc.fillColor(COLORS.text).fontSize(16).text(`Target: ${result.target}`, 50, 110);
  doc.fillColor(COLORS.muted).fontSize(10)
    .text(`URL: ${result.url}`)
    .text(`Scanned: ${new Date(result.scanDate).toLocaleString()}`)
    .text(`IP: ${result.ipAddress ?? 'N/A'}   •   Hosting: ${result.hostingProvider ?? 'N/A'}   •   Country: ${result.country ?? 'N/A'}`);

  // Risk score box
  const boxY = 175;
  doc.roundedRect(50, boxY, 240, 70, 8).fill('#f3f4f6');
  doc.fillColor(COLORS.text).fontSize(11).text('Risk Score', 65, boxY + 12);
  doc.fillColor(levelColor(result.riskLevel)).fontSize(34).text(`${result.riskScore}`, 65, boxY + 26);
  doc.fillColor(COLORS.muted).fontSize(10).text('/ 100', 130, boxY + 48);

  doc.roundedRect(310, boxY, 235, 70, 8).fill('#f3f4f6');
  doc.fillColor(COLORS.text).fontSize(11).text('Risk Level', 325, boxY + 12);
  doc.fillColor(levelColor(result.riskLevel)).fontSize(24).text(result.riskLevel, 325, boxY + 30);

  doc.moveDown(2);
  let y = boxY + 95;

  // Summary
  doc.fillColor(COLORS.text).fontSize(13).text('Summary', 50, y);
  y += 18;
  doc.fillColor(COLORS.muted).fontSize(10).text(result.summary, 50, y, { width: 495 });
  y = doc.y + 15;

  const section = (title: string) => {
    if (y > 720) {
      doc.addPage();
      y = 50;
    }
    doc.fillColor(COLORS.primary).fontSize(13).text(title, 50, y);
    y += 18;
  };
  const row = (label: string, value: string) => {
    if (y > 760) {
      doc.addPage();
      y = 50;
    }
    doc.fillColor(COLORS.text).fontSize(10).text(label, 50, y, { width: 180, continued: false });
    doc.fillColor(COLORS.muted).fontSize(10).text(value, 235, y, { width: 310 });
    y = doc.y + 4;
  };

  section('Infrastructure');
  row('DNS Resolved', result.dns.resolved ? 'Yes' : 'No');
  row('IPv4', result.dns.ipv4.join(', ') || 'N/A');
  row('Name Servers', result.dns.nameServers.join(', ') || 'N/A');
  row('Server', result.http.server ?? 'N/A');
  row('Technologies', result.http.technologies.join(', ') || 'N/A');
  row('CMS', result.http.cms ?? 'None detected');

  section('TLS / SSL');
  row('Valid Certificate', result.ssl.valid ? 'Yes' : 'No');
  row('Issuer', result.ssl.issuer ?? 'N/A');
  row('Expires', result.ssl.validTo ?? 'N/A');
  row('Days Until Expiry', result.ssl.daysUntilExpiry?.toString() ?? 'N/A');

  section('WHOIS');
  row('Registrar', result.whois.registrar ?? 'N/A');
  row('Created', result.whois.createdDate ?? 'N/A');
  row('Domain Age (days)', result.whois.domainAgeDays?.toString() ?? 'N/A');

  section('Security Headers');
  row('Score', `${result.securityHeaders.score}/100`);
  for (const h of result.securityHeaders.headers) {
    row(h.name, h.present ? 'Present' : 'Missing');
  }

  section('Open Ports');
  if (result.ports.length === 0) {
    row('Open Ports', 'None detected');
  } else {
    for (const p of result.ports) {
      row(`${p.port} (${p.service})`, p.risky ? 'OPEN — risky' : 'open');
    }
  }

  if (result.aiThreats.length > 0) {
    section('AI Threat Analysis (Gemini)');
    for (const t of result.aiThreats) {
      row(`${t.name} [${t.severity}]`, `${t.type} — ${t.description}`);
    }
  }

  section('Risk Breakdown');
  for (const item of result.riskBreakdown) {
    row(item.label, `${item.points > 0 ? '+' : ''}${item.points} — ${item.note}`);
  }

  // Footer
  doc.fontSize(8).fillColor(COLORS.muted).text(
    'Generated by AI Security Intelligence Platform',
    50,
    doc.page.height - 40,
    { align: 'center', width: doc.page.width - 100 },
  );

  return doc;
}
